apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
stringData:
  AUTH_MONGODB_URI: ${AUTH_MONGODB_URI}
  REDIS_URL: ${REDIS_URL}
  RABBITMQ_URL: ${RABBITMQ_URL}

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt
type: Opaque
stringData:
  JWT_SECRET: ${JWT_SECRET}

---
apiVersion: v1
kind: Secret
metadata:
  name: google
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  GOOGLE_REFRESH_TOKEN: ${GOOGLE_REFRESH_TOKEN}
  EMAIL_USER: ${EMAIL_USER}

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-secret
type: Opaque
stringData:
  MISTRAL_API_KEY: ${MISTRALAI_API_KEY}
