apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
stringData:
  AUTH_MONGODB_URI: ${AUTH_MONGODB_URI}
  REDIS_URL: ${REDIS_URL}
  RABBITMQ_URL: ${RABBITMQ_URL}
  AI_DATABASE_URL: ${AI_DATABASE_URL}
  SANDBOX_MONGODB_URI: ${SANDBOX_MONGODB_URI}

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt
type: Opaque
stringData:
  JWT_SECRET: ${JWT_SECRET}

---
apiVersion: v1
kind: Secret
metadata:
  name: google
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  GOOGLE_REFRESH_TOKEN: ${GOOGLE_REFRESH_TOKEN}
  EMAIL_USER: ${EMAIL_USER}
  SESSION_SECRET: ${SESSION_SECRET}
  GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-secret
type: Opaque
stringData:
  MISTRAL_API_KEY: ${MISTRALAI_API_KEY}


---
apiVersion: v1
kind: Secret
metadata:
  name: aws
type: Opaque
stringData:
  AWS_REGION: ${AWS_REGION}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  S3_BUCKET_NAME: ${S3_BUCKET_NAME}
